version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_container
    restart: always
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
      - SECRET_KEY=43939478e74683d1a40eab9772216711c5354d4728e7a6c80dcb084ae5ca4b8f
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_container
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5001
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    depends_on:
      - backend
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_container
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /foo/swagger.yaml
    volumes:
      - ./swagger.yaml:/foo/swagger.yaml
volumes:
  postgres_data:
  node_modules_frontend: