services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres

  frontend:
    image: node:18  # Используем Node.js для React
    container_name: react_container
    working_dir: /app
    volumes:
      - ./frontend:/app  # Монтируем локальную папку с React-приложением
    ports:
      - "3000:3000"  # React по умолчанию работает на порту 3000
    environment:
      - NODE_ENV=development  # Режим разработки
    command: >
      sh -c "npm install && npm start"  # Устанавливаем зависимости и запускаем приложение
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
